import pandas as pd

# Diccionario de renombrado de columnas
column_rename = {
    "ANIO": "Año de la encuesta",
    "MES": "Mes de la encuesta",
    "CONGLOMERADO": "Número del conglomerado",
    "MUESTRA": "Nº de Sub Muestra",
    "SELVIV": "Número de selección de la vivienda",
    "HOGAR": "Hogar",
    "REGION": "Región",
    "LLAVE_PANEL": "Código de persona panel",
    "ESTRATO": "Estrato geográfico",
    "C201": "Código de persona",
    "C203": "203. ¿CUÁL ES LA RELACIÓN DE PARENTESCO CON EL JEFE DEL HOGAR?",
    "C204": "204. ¿ES MIEMBRO DEL HOGAR?",
    "C205": "205. ¿SE ENCUENTRA AUSENTE DEL HOGAR 30 DÍAS O MÁS?",
    "C206": "206. ¿ESTÁ PRESENTE EN EL HOGAR 30 DÍAS O MÁS?",
    "C207": "207. SEXO",
    "C208": "208. ¿QUÉ EDAD TIENE EN AÑOS CUMPLIDOS? Años",
    "C300n": "CÓDIGO DE PERSONA (MODULO DE EMPLEO)",
    "NROINF": "CÓDIGO DE INFORMANTE (MODULO EMPLEO)",
    "C301_DIA": "301. ¿CUÁL ES LA FECHA DE SU NACIMIENTO? - DIA",
    "C301_MES": "301. ¿CUÁL ES LA FECHA DE SU NACIMIENTO? - MES",
    "C301_ANIO": "301. ¿CUÁL ES LA FECHA DE SU NACIMIENTO? - AÑO",
    "C303": "303. LA SEMANA PASADA, DEL……AL....,¿TUVO UD. ALGÚN TRABAJO? (Sin contar los quehaceres del hogar)",
    "C304": "304. AUNQUE NO TRABAJÓ LA SEMANA PASADA, ¿TIENE ALGÚN EMPLEO FIJO AL QUE PRÓXIMAMENTE VOLVERÁ?",
    "C305": "305. AUNQUE NO TRABAJÓ LA SEMANA PASADA, ¿TIENE ALGÚN NEGOCIO PROPIO AL QUE PRÓXIMAMENTE VOLVERÁ?",
    "C306_1": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 1? Trabajando en algún negocio propio o de un familiar?",
    "C306_2": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 2? Ofreciendo algún servicio?",
    "C306_3": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 3. Haciendo algo en casa para vender?",
    "C306_4": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 4? Vendiendo productos de belleza, ropa, joyas, entre otros?",
    "C306_5": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 5? Realizando alguna labor artesanal?",
    "C306_6": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 6? Haciendo prácticas pagadas en un centro de trabajo?",
    "C306_7": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 7? Trabajando para un hogar particular?",
    "C306_8": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 8? Fabricando algún producto?",
    "C306_9": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 9? Realizando labores remuneradas en la chacra o cuidado de animales?",
    "C306_10": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 10? Ayudando a un familiar de su hogar, sin remuneración?",
    "C306_10A": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 10?A. Ayudando con el empleo de algún miembro de su hogar?",
    "C306_11": "306. LA SEMANA PASADA, ¿REALIZÓ ALGUNA ACTIVIDAD AL MENOS UNA HORA PARA OBTENER INGRESOS EN DINERO O EN ESPECIE, COMO: 11? Otra?",
    "C308_COD": "308. ¿CUÁL ES LA OCUPACIÓN PRINCIPAL QUE DESEMPEÑÓ? - CODIGO",
    "C309_COD": "309. ¿A QUÉ SE DEDICA EL NEGOCIO, ORGANISMO O EMPRESA EN LA QUE TRABAJÓ EN SU OCUPACIÓN PRINCIPAL? CODIGO",
    "C310": "310. UD. SE DESEMPEÑÓ EN SU OCUPACIÓN PRINCIPAL O NEGOCIO COMO:",
    "C311": "311. EN SU OCUPACIÓN PRINCIPAL, ¿UD. TRABAJÓ PARA:",
    "C312": "312. El negocio o empresa donde trabaja, se encuentra registrado en la sunat, como:",
    "C313": "313. El negocio o empresa donde trabaja, lleva las cuentas por medio de libros contables exigidos por la SUNAT o sistema de contabilidad",
    "C317": "317. EN SU TRABAJO, NEGOCIO O EMPRESA, INCLUYÉNDOSE UD., ¿LABORARON:",
    "C317A": "317. EN SU TRABAJO, NEGOCIO O EMPRESA, INCLUYÉNDOSE UD., ¿LABORARON: N° DE PERSONAS",
    "C318_1": "318. ¿CUÁNTAS HORAS TRABAJÓ LA SEMANA PASADA, EN SU OCUPACIÓN PRINCIPAL? (DÍA POR DÍA) - Domingo",
    "C318_2": "318. ¿CUÁNTAS HORAS TRABAJÓ LA SEMANA PASADA, EN SU OCUPACIÓN PRINCIPAL? (DÍA POR DÍA) - Lunes",
    "C318_3": "318. ¿CUÁNTAS HORAS TRABAJÓ LA SEMANA PASADA, EN SU OCUPACIÓN PRINCIPAL? (DÍA POR DÍA) - Martes",
    "C318_4": "318. ¿CUÁNTAS HORAS TRABAJÓ LA SEMANA PASADA, EN SU OCUPACIÓN PRINCIPAL? (DÍA POR DÍA) - Miércoles",
    "C318_5": "318. ¿CUÁNTAS HORAS TRABAJÓ LA SEMANA PASADA, EN SU OCUPACIÓN PRINCIPAL? (DÍA POR DÍA) - Jueves",
    "C318_6": "318. ¿CUÁNTAS HORAS TRABAJÓ LA SEMANA PASADA, EN SU OCUPACIÓN PRINCIPAL? (DÍA POR DÍA) - Viernes",
    "C318_7": "318. ¿CUÁNTAS HORAS TRABAJÓ LA SEMANA PASADA, EN SU OCUPACIÓN PRINCIPAL? (DÍA POR DÍA) - Sábado",
    "whoraT": "TOTAL, DE HORAS TRABAJADAS",
    "C330": "330. EN TOTAL UD. TRABAJÓ…………… HORAS LA SEMANA PASADA. ¿NORMALMENTE TRABAJA ESAS HORAS A LA SEMANA?",
    "C331": "331. NORMALMENTE, ¿CUÁNTAS HORAS TRABAJA A LA SEMANA EN TODAS SUS OCUPACIONES?",
    "C333": "¿TUVO LA VOLUNTAD DE TRABAJAR MAS HORAS Y ADEMÁS ESTUVO DISPONIBLE PARA HACERLO?",
    "C335": "335. LA SEMANA PASADA, ¿ESTUVO UD. BUSCANDO OTRO TRABAJO?",
    "C338": "338. EN SU OCUPACIÓN PRINCIPAL, ¿A UD. LE PAGAN:",
    "C339_1": "339_1 ¿CUÁNTO FUE SU INGRESO TOTAL EN EL (LA)…ANTERIOR, INCLUYENDO HORAS EXTRAS, BONIFICACIONES, PAGO POR CONCEPTO DE REFRIGERIO, MOVILIDAD, COMISIONES, ENTRE OTROS? A. Ingreso total - Monto S/.",
    "C341_T": "341_T EN SU OCUPACIÓN PRINCIPAL, ¿CON QUÉ FRECUENCIA Y EN CUÁNTO ESTIMARÍA UD. EL PAGO EN ESPECIES?: VALOR ESTIMADO TOTAL",
    "C342": "342. EN SU OCUPACIÓN PRINCIPAL, ¿CUÁL FUE LA GANANCIA NETA EN EL MES ANTERIOR?",
    "C344": "344 ¿EN CUÁNTO ESTIMA UD. EL VALOR DE LOS PRODUCTOS UTILIZADOS PARA SU CONSUMO EN EL MES ANTERIOR?",
    "C345_1": "345. ¿CUÁNTO FUE SU INGRESO TOTAL EN EL MES ANTERIOR, INCLUYENDO HORAS EXTRAS, BONIFICACIONES, PAGO POR CONCEPTO DE REFRIGERIO, MOVILIDAD, COMISIONES, ENTRE OTROS. EN SU(S) OCUPACIÓN(ES) SECUNDARIA(S)? A. MONTO DEL INGRESO TOTAL",
    "C347_T": "347 EN SU OCUPACIÓN SECUNDARIA ¿CON QUÉ FRECUENCIA Y EN CUÁNTO ESTIMARÍA UD. EL PAGO EN ESPECIES?: VALOR ESTIMADO TOTAL",
    "C348": "348. EN SU(S) OCUPACIÓN(ES) SECUNDARIA(S), ¿CUÁL FUE SU GANANCIA NETA EN EL MES ANTERIOR?_Soles",
    "C350": "350. EN SU OCUPACIÓN SECUNDARIA ¿EN CUANTO ESTIMA UD, EL VALOR DE LOS PRODUCTOS UTILIZADOS PARA SU CONSUMO EN EL MES ANTERIOR?: VALOR ESTIMADO TOTAL",
    "C352": "352. LA SEMANA PASADA, ¿HIZO ALGO PARA CONSEGUIR TRABAJO?",
    "C353": "353. ¿QUÉ ESTUVO HACIENDO LA SEMANA PASADA?",
    "C354": "354. LA SEMANA PASADA, ¿QUERÍA UD. TRABAJAR?",
    "C355": "355. LA SEMANA PASADA, ¿ESTUVO DISPONIBLE PARA TRABAJAR?",
    "C356": "356. ¿POR QUÉ NO BUSCÓ TRABAJO?",
    "C357_I": "357. LA SEMANA PASADA, ¿QUE HIZO PARA CONSEGUIR TRABAJO? REGISTRE EL CÓDIGO DE LA GESTIÓN MÁS IMPORTANTE",
    "C358": "358. ¿CUÁNTAS SEMANAS HA ESTADO BUSCANDO TRABAJO, SIN INTERRUPCIONES?",
    "C359": "359. ¿HA TRABAJADO ANTES?",
    "SEGURO1": "EL SISTEMA DE SEGURO DE SALUD AL CUAL ESTA AFILIADO ES:",
    "C366": "366. ¿CUÁL ES EL ÚLTIMO AÑO O GRADO DE ESTUDIOS Y NIVEL QUE APROBÓ?",
    "C366_1": "366. ¿CUÁL ES EL ÚLTIMO AÑO O GRADO DE ESTUDIOS Y NIVEL QUE APROBÓ? Año",
    "C366_2": "366. ¿CUÁL ES EL ÚLTIMO AÑO O GRADO DE ESTUDIOS Y NIVEL QUE APROBÓ? Grado",
    "C375_1": "375. ¿TIENE UD. LIMITACIONES DE FORMA PERMANENTE, PARA: 1? Moverse o caminar, para usar brazos o piernas?",
    "C375_2": "375. ¿TIENE UD. LIMITACIONES DE FORMA PERMANENTE, PARA: 2? Ver, aun usando anteojos?",
    "C375_3": "375. ¿TIENE UD. LIMITACIONES DE FORMA PERMANENTE, PARA: 3? Hablar o comunicarse, aun usando la lengua de señas u otro?",
    "C375_4": "375. ¿TIENE UD. LIMITACIONES DE FORMA PERMANENTE, PARA: 4? Oír, aun usando audífonos?",
    "C375_5": "375. ¿TIENE UD. LIMITACIONES DE FORMA PERMANENTE, PARA: 5. Entender o aprender (concentrarse y recordar)?",
    "C375_6": "375. ¿TIENE UD. LIMITACIONES DE FORMA PERMANENTE, PARA: 6. Relacionarse con los demás, por sus pensamientos, sentimientos, emociones o conductas?",
    "C376": "376. ¿CUÁL ES EL IDIOMA O LENGUA MATERNA QUE APRENDIÓ EN SU NIÑEZ?",
    "C377": "377. POR SUS COSTUMBRES Y SUS ANTEPASADOS, ¿UD. SE SIENTE O SE CONSIDERA:",
    "OCUP300": "Indicador de Condición de Actividad",
    "I339_1": "Ingreso mensual monetario de la actividad principal por trabajador dependiente (Imputación de la variable C339_1)",
    "D341_T": "Ingreso mensual en especies de la actividad principal por trabajador dependiente (valorizado) (Mensualización de la variable C341_T)",
    "I342": "Ingreso mensual monetario de la actividad principal por trabajador independiente (Imputación de la variable C342)",
    "D344": "Ingreso mensual en especies de la actividad principal por trabajador independiente (valorizado) (Mensualización de la variable C344)",
    "I345_1": "Ingreso mensual monetario de la actividad secundaria por trabajador dependiente (Imputación de la variable C345_1)",
    "I348": "Ingreso mensual monetario de la actividad secundaria por trabajador independiente (Imputación de la variable C348)",
    "D347_T": "Ingreso mensual en especies de la actividad secundaria por trabajador dependiente (Mensualización de la variable C347_T)",
    "D350": "Ingreso mensual en especies de la actividad secundaria por trabajador independiente (valorizado) (Mensualización de la variable C350)",
    "INGTOT": "Ingreso Total Mensual",
    "INGTOTP": "Ingresos totales",
    "ingtrabw": "Ingreso principal mensual",
    "RESIDENT": "Residente Habitual",
    "fa_efm24": "Factor Trimestral Ene-Feb-Mar24",
}

# Convertir el diccionario a un DataFrame
descriptions_df = pd.DataFrame(list(column_rename.items()), columns=["column_name", "description"])

# Guardar el DataFrame en un CSV
descriptions_file_path = r"D:\FOREX\MT5_1\MQL5\Experts\Projects\Sharing-Projects\Misc\INEI\column_descriptions.csv"
descriptions_df.to_csv(descriptions_file_path, index=False)

# Mostrar el CSV generado
descriptions_df.head()
